name: ci-test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [gcc]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

        with:
          submodules: recursive

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gfortran fftw3 libfftw3-dev libnetcdf-dev \
                                  libnetcdf-c++4 libnetcdf-c++4-dev cmake \
                                  libboost-dev libopenmpi-dev openmpi-bin python3-pip
          pip3 install --user numpy netcdf4

      # Configure and build without MPI
      - name: Configure and build DP + CPU
        run: |
          mkdir build_dp_cpu
          cd build_dp_cpu
          cmake -DSYST=ubuntu_20lts ..
          make -j 4
          cd ..

      # Configure and build without MPI, in SP
      - name: Configure and build SP + CPU
        run: |
          mkdir build_sp_cpu
          cd build_sp_cpu
          cmake -DSYST=ubuntu_20lts -DUSESP=true ..
          make -j 4
          cd ..

      # Configure and build with MPI
      - name: Configure and build SP + CPUMPI
        run: |
          mkdir build_sp_cpumpi
          cd build_sp_cpumpi
          cmake -DSYST=ubuntu_20lts -DUSESP=true -DUSEMPI=true ..
          make -j 4
          cd ..

      # Run tests
      - name: Run tests
        run: |
          cd cases
          python3 run_ci_tests.py

